const CREATE_NOTE = "CREATE_NOTE";
const DELETE_NOTE = "DELETE_NOTE";
const UPDATE_NOTE = "UPDATE_NOTE";
const ARCHIVE_NOTE = "ARCHIVE_NOTE";
const DELETE_ALL_NOTES = "DELETE_ALL_NOTES";
const ARCHIVE_ALL_NOTES = "ARCHIVE_ALL_NOTES";

export {
	ARCHIVE_ALL_NOTES,
	DELETE_ALL_NOTES,
	DELETE_NOTE,
	ARCHIVE_NOTE,
	CREATE_NOTE,
	UPDATE_NOTE
};
